DROP TABLE USER_ACCOUNT;
CREATE TABLE USER_ACCOUNT
(
	USERNAME VARCHAR2(50)
		CONSTRAINT USER_ACCOUNT_PK
			PRIMARY KEY,
	PASSWORD VARCHAR2(50) NOT NULL
);
COMMIT;

INSERT INTO USER_ACCOUNT (USERNAME, PASSWORD) VALUES ('COSTAS', 'SECRETPASSWORD');
INSERT INTO USER_ACCOUNT (USERNAME, PASSWORD) VALUES ('PANOS', 'STRONGPASSWORD');
COMMIT;

DROP TABLE STUDENT;
CREATE TABLE STUDENT
(
    SID   VARCHAR2(5)  NOT NULL
        CONSTRAINT PK_STUDENT
            PRIMARY KEY,
    NAME  VARCHAR2(15) NOT NULL,
    MAJOR VARCHAR2(10),
    QPA INTEGER
);

INSERT INTO STUDENT (SID, NAME, QPA, MAJOR) VALUES ('123', 'JOHN', 3, 'CS');
INSERT INTO STUDENT (SID, NAME, QPA, MAJOR) VALUES ('124', 'MARY', 3, 'CS');
INSERT INTO STUDENT (SID, NAME, QPA, MAJOR) VALUES ('126', 'SAM', 2, 'CS');
INSERT INTO STUDENT (SID, NAME, QPA, MAJOR) VALUES ('129', 'JULIE', 2, 'MATH');
INSERT INTO STUDENT (SID, NAME, QPA, MAJOR) VALUES ('11', 'COSTA', 3, 'CS');
commit;
